---
github_user: hasansezertasan
github_repo_name: example
author_full_name: Hasan Sezer Taşan
author_given_names: Hasan Sezer
author_family_names: Taşan
author_email: hasansezertasan@gmail.com
short_description: A Python project example.
package_keywords: "example, demo"
preset: library
