#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["copier"]
# ///
"""The single render entrypoint for the copier-pyproject template (ADR-031).

Every consumer that needs "render this template with these answers" goes
through :func:`render` — the pytest harness fixture (``tests/conftest.py``),
the ``template-ci.yml`` generate-and-run matrix, the committed docs artifacts
(:func:`regenerate`), and the authoring watch loop (:func:`watch`). Four
issues each proposed their own ``copier copy`` invocation (#181/#183/#164/#184)
on top of the one the render harness already had (#182); this module is the
primitive they all call instead.

Run it directly (PEP 723 metadata provides copier)::

    uv run tools/render.py render ../rendered --data include_web=true
    uv run tools/render.py regenerate
    uv run --with watchfiles tools/render.py watch

or import it (the repo root is on ``sys.path`` under pytest)::

    from tools.render import render

Note: with ``ref="HEAD"`` Copier renders from this repo's git tree and includes
uncommitted working-tree changes (it emits a ``DirtyLocalWarning``), so every
consumer reflects the current working copy of ``copier.yml`` / ``template/``.
"""

from __future__ import annotations

import argparse
import shutil
import sys
import tempfile
from pathlib import Path
from typing import TYPE_CHECKING, Iterable, Sequence

import copier
import yaml  # a transitive dependency of copier

if TYPE_CHECKING:
    from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent

# The maintainer-facing answers file, used by the `example` mise task and the
# CI matrix. Programmatic renders (the pytest harness) deliberately do *not*
# load it: the harness asserts on a neutral, stable identity that does not move
# when a maintainer edits their own example inputs.
DATA_FILE = REPO_ROOT / ".example-input.yml"

# Required questions (no defaults) — supplied so renders stay non-interactive.
IDENTITY = {
    "github_user": "octocat",
    "github_repo_name": "example",
    "author_full_name": "Octo Cat",
    "author_email": "octo@example.com",
}

# The four archetype presets (ADR-016), documented in the generated tree page.
PRESETS = ("library", "tool", "web", "full")

# Committed derived artifact: the real file set each preset renders (#164).
TREE_PAGE = REPO_ROOT / "docs" / "generated-project-trees.md"

# Scratch render target for the authoring watch loop (#184), gitignored.
WATCH_OUT = REPO_ROOT / ".watch-render"
WATCH_PATHS = (REPO_ROOT / "template", REPO_ROOT / "copier.yml", DATA_FILE)


def render(
    dst: Path | str,
    *,
    data_file: Path | str | None = None,
    ref: str = "HEAD",
    quiet: bool = True,
    **answers: Any,
) -> Path:
    """Render the template into ``dst`` and return that path.

    Answers layer in increasing precedence: :data:`IDENTITY`, ``data_file``
    (when given), then explicit keyword ``answers`` — e.g.
    ``render(dst, preset="full")`` or
    ``render(dst, include_worker=True, worker_broker="redis")``.
    """
    data: dict[str, Any] = dict(IDENTITY)
    if data_file is not None:
        data.update(yaml.safe_load(Path(data_file).read_text(encoding="utf-8")) or {})
    data.update(answers)
    copier.run_copy(
        str(REPO_ROOT),
        str(dst),
        data=data,
        defaults=True,
        overwrite=True,
        vcs_ref=ref,
        quiet=quiet,
    )
    return Path(dst)


def tree(root: Path) -> list[str]:
    """Sorted, repo-relative POSIX paths of every file rendered under ``root``."""
    return sorted(
        p.relative_to(root).as_posix() for p in root.rglob("*") if p.is_file()
    )


def tree_page(workdir: Path, presets: Iterable[str] = PRESETS) -> str:
    """Build the Markdown page listing the file set each preset renders.

    ``workdir`` holds one throwaway render per preset. No ``<details>`` or other
    inline HTML: the repo's markdownlint config leaves MD033 enabled.
    """
    lines = [
        "<!-- Generated by `uv run tools/render.py regenerate` — do not edit. -->",
        "",
        "# Generated project trees",
        "",
        "The exact file set each preset renders, captured from a real `copier copy`",
        "run rather than typed by hand (see [ADR-031](adr/031-single-render-entrypoint.md)).",
        "Presets are defined by `preset_map` in `copier.yml`",
        "([ADR-016](adr/016-archetype-based-presets.md)); the identity answers are the",
        "harness defaults (`octocat`/`example`), so `example` below is the package name.",
        "",
        "Regenerate with `mise run regenerate`. `tests/test_doc_trees.py` fails when this",
        "page drifts from a fresh render.",
        "",
    ]
    for preset in presets:
        paths = tree(render(workdir / preset, preset=preset))
        lines += [
            f"## {preset}",
            "",
            f"{len(paths)} files.",
            "",
            "```text",
            *paths,
            "```",
            "",
        ]
    return "\n".join(lines)


def regenerate(workdir: Path) -> list[Path]:
    """Rewrite every committed derived artifact; return the paths written.

    The generate-and-verify half of the convention (#181): a fresh render is the
    source of truth, and ``tests/test_doc_trees.py`` is the drift guard that
    fails when a committed artifact no longer matches one. New derived artifacts
    plug in here rather than growing a second generator.
    """
    TREE_PAGE.write_text(tree_page(workdir), encoding="utf-8")
    return [TREE_PAGE]


def watch(out: Path, **answers: Any) -> int:
    """Re-render into ``out`` on every save under :data:`WATCH_PATHS` (#184).

    Local authoring aid only — never a gate. ``watchfiles`` is not part of this
    script's dependencies, so the caller supplies it
    (``uv run --with watchfiles tools/render.py watch``).
    """
    try:
        from watchfiles import watch as watch_files
    except ImportError:  # pragma: no cover - authoring aid, not covered in CI
        print(
            "watch needs watchfiles: uv run --with watchfiles tools/render.py watch",
            file=sys.stderr,
        )
        return 1

    def rebake() -> None:
        shutil.rmtree(out, ignore_errors=True)
        try:
            render(out, data_file=DATA_FILE, quiet=False, **answers)
        except Exception as exc:  # noqa: BLE001 - keep the loop alive on any render error
            print(f"[watch] FAILED: {exc}", flush=True)
        else:
            print(f"[watch] rebaked -> {out}", flush=True)

    print(f"[watch] watching {', '.join(str(p) for p in WATCH_PATHS)}", flush=True)
    rebake()
    # watchfiles batches events (50ms debounce by default), so a multi-file save
    # is one rebake.
    for _ in watch_files(*WATCH_PATHS):
        rebake()
    return 0


def _answers(pairs: Sequence[str]) -> dict[str, Any]:
    """Parse ``--data key=value`` pairs the way the copier CLI does."""
    data: dict[str, Any] = {}
    for pair in pairs:
        key, sep, value = pair.partition("=")
        if not sep:
            raise SystemExit(f"--data expects key=value, got {pair!r}")
        data[key] = yaml.safe_load(value)  # so true/false/123 keep their types
    return data


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    one = sub.add_parser("render", help="render the template into a directory")
    one.add_argument("dst", type=Path)
    one.add_argument("--data", action="append", default=[], metavar="KEY=VALUE")
    one.add_argument("--data-file", type=Path, default=DATA_FILE)
    one.add_argument("--ref", default="HEAD")

    sub.add_parser("regenerate", help="rewrite the committed derived artifacts")

    loop = sub.add_parser("watch", help="re-render a scratch project on every save")
    loop.add_argument("--out", type=Path, default=WATCH_OUT)
    loop.add_argument("--data", action="append", default=[], metavar="KEY=VALUE")

    args = parser.parse_args(argv)

    if args.command == "render":
        dst = render(
            args.dst,
            data_file=args.data_file,
            ref=args.ref,
            quiet=False,
            **_answers(args.data),
        )
        print(f"rendered -> {dst}")
        return 0
    if args.command == "watch":
        return watch(args.out, **_answers(args.data))

    # regenerate: renders into a throwaway dir under the system temp root.
    with tempfile.TemporaryDirectory() as workdir:
        for path in regenerate(Path(workdir)):
            print(f"regenerated -> {path.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
